title: "OX News"
description: "Mais inteligente em 5 minutos. Somos uma newslatter gratuita, que tem por objetivo te trazer tudo que você precisa saber para começar o seu dia bem e informado."
permalink: '/p/:title.html'
img: "https://i.ytimg.com/vi/3dacSexuyCo/hq720.jpg" #https://picsum.photos/460/270?https://i1.wp.com/4kwallpapers.com/images/walls/thumbs_2t/4700.jpg
baseurl: ""
url: "https://newslatter.souox.com"
markdown: kramdown
theme: minima
safe: false

author_id: "ox-news"
author_name: "OX NEWS"
author_image: "https://souox.com/file/img/header-oxnews.png?v=2"
author_bio: "Mais inteligente em 5 minutos. Somos uma newslatter gratuita, que tem por objetivo te trazer tudo que você precisa saber para começar o seu dia bem e informado."

# Define regras automáticas para arquivos específicos
defaults:
  - scope:
      path: ""       # Aplica-se a todo o projeto
      type: "posts"  # Alvo: apenas os arquivos dentro da pasta _posts
    values:
      layout: "post" # Injeta automaticamente o layout padrão do seu template
